version: '3.8'

services:
  tts-webapp:
    build: .
    image: tts-webapp
    container_name: tts-webapp
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
